const lang = {
  en: {
    searchText: "What would you like to watch today?",
    search: "Search",
    movieList1: "Now Playing Movies",
    movieList2: "Popular Movies",
    movieList3: "Suggested for You",
    movieList4: "Movies You Might Like",
    movieList5: "Top Picks Today",
    movieList6: "Upcoming Movies",
    movieList7: "Critically Acclaimed Shows",
  },
  hi: {
    searchText: "आज आप क्या देखना चाहेंगे?",
    search: "खोजें",
    movieList1: "अभी चल रही फ़िल्में",
    movieList2: "लोकप्रिय फ़िल्में",
    movieList3: "आपके लिए सुझाई गई",
    movieList4: "आपको पसंद आ सकती हैं",
    movieList5: "आज के टॉप पिक्स",
    movieList6: "आने वाली फ़िल्में",
    movieList7: "समीक्षकों द्वारा सराही गई शृंखलाएँ",
  },
  es: {
    searchText: "¿Qué te gustaría ver hoy?",
    search: "Buscar",
    movieList1: "Películas en cartelera",
    movieList2: "Películas populares",
    movieList3: "Sugerencias para ti",
    movieList4: "Películas que podrían gustarte",
    movieList5: "Mejores selecciones de hoy",
    movieList6: "Próximos estrenos",
    movieList7: "Series aclamadas por la crítica",
  },
  fr: {
    searchText: "Que voulez-vous regarder aujourd'hui ?",
    search: "Rechercher",
    movieList1: "Films à l'affiche",
    movieList2: "Films populaires",
    movieList3: "Suggestions pour vous",
    movieList4: "Films qui pourraient vous plaire",
    movieList5: "Meilleures sélections du jour",
    movieList6: "Films à venir",
    movieList7: "Séries saluées par la critique",
  },
  de: {
    searchText: "Was möchtest du heute schauen?",
    search: "Suche",
    movieList1: "Filme im Kino",
    movieList2: "Beliebte Filme",
    movieList3: "Für dich vorgeschlagen",
    movieList4: "Filme, die dir gefallen könnten",
    movieList5: "Top-Empfehlungen heute",
    movieList6: "Kommende Filme",
    movieList7: "Von der Kritik gefeierte Serien",
  },
  ja: {
    searchText: "今日は何を見たいですか？",
    search: "検索",
    movieList1: "上映中の映画",
    movieList2: "人気の映画",
    movieList3: "あなたへのおすすめ",
    movieList4: "気に入りそうな映画",
    movieList5: "本日のトップピック",
    movieList6: "近日公開の映画",
    movieList7: "批評家絶賛のドラマ",
  },
  zh: {
    searchText: "今天想看什么？",
    search: "搜索",
    movieList1: "正在上映的电影",
    movieList2: "热门电影",
    movieList3: "为你推荐",
    movieList4: "你可能喜欢的电影",
    movieList5: "今日精选",
    movieList6: "即将上映",
    movieList7: "备受好评的剧集",
  },
};

export default lang;
